### ISSUE TITLE
Show max sell price and total

### ISSUE THREAD

**Issue by JohnTheCoolingFan** [RemainNA/cargo-manifest#7]
Suggestion for showing total cost of the cargo based on max sell price (like on inara.cz)

**Comment by RemainNA** [comment]
Will include in the next release, pulling from the same source for average prices (eddb.io)

**Comment by RemainNA** [comment]
@JohnTheCoolingFan Checking to make sure my implementation is similar to what you have in mind, do you want the max sell price to be displayed to the right of each commodity per unit (like average is right now), beneath the cargo list as a cumulative max value of all current cargo, both, or something else?

**Comment by JohnTheCoolingFan** [comment]
I'd like to see both, thank you for your work!

**Comment by RemainNA** [comment]
Added in 235d12b8036965af78a46700c82cc8afa8df3767.  Thanks for the suggestion!
