### ISSUE TITLE
New commodities type

### ISSUE THREAD

**Issue by RDaneliya** [RemainNA/cargo-manifest#8]
There are 5 new commodities from EDDN:
* thargoidtissuesampletype5 (I believe that's Orthrus type tissue sample)
* thargoidgeneratortissuesample (New thargoid generator sample)
* ancientrelictg (Idk what's that) 
* classifiedexperimentalequipment (Classified experimental data)
* unocuppiedescapepod (Unoccupied escape pod) 

Please update items list

**Comment by RemainNA** [comment]
Updating list and also updating the plugin to self-update in the future so new releases are no longer required

**Comment by RemainNA** [comment]
Updated in 2b0af5db91933b6aa674a9a355d90d60746c63ef, auto-updates in 3034d5f8178964dce91da74a8b6939cb010acbee.
